# Generated by Django 5.0 on 2024-10-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='student_profile')),
                ('full_name', models.CharField(max_length=200)),
                ('cohort', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=200)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
